import type { Tool } from '@/types'

export const CATEGORY_ICON_BG: Record<string, string> = {
  'Essentials': '#FFF0DC',
  'Edit & Organize': '#DBEAFE',
  'Security': '#FEE2E2',
  'Convert': '#D1FAE5',
  'AI Tools': '#EDE9FE',
  'Utilities': '#F3F4F6',
}

export const CATEGORIES = [
  'All Tools',
  'Essentials',
  'Edit & Organize',
  'Security',
  'Convert',
  'AI Tools',
  'Utilities',
]

export const TOOLS: Tool[] = [
  // ── Essentials ──────────────────────────────────────────────────────────────
  {
    id: 'merge-pdf',
    name: 'Merge PDF',
    icon: '🔀',
    category: 'Essentials',
    desc: 'Combine multiple PDFs into one',
    slug: 'merge-pdf',
    colorBg: '#FFF0DC',
  },
  {
    id: 'split-pdf',
    name: 'Split PDF',
    icon: '✂️',
    category: 'Essentials',
    desc: 'Extract pages or split by range',
    slug: 'split-pdf',
    colorBg: '#FFF0DC',
  },
  {
    id: 'compress-pdf',
    name: 'Compress PDF',
    icon: '📦',
    category: 'Essentials',
    desc: 'Reduce file size without quality loss',
    slug: 'compress-pdf',
    colorBg: '#FFF0DC',
  },
  {
    id: 'pdf-to-jpg',
    name: 'PDF → Images',
    icon: '🖼️',
    category: 'Essentials',
    desc: 'Convert PDF pages to JPG or PNG',
    slug: 'pdf-to-jpg',
    colorBg: '#FFF0DC',
  },
  {
    id: 'jpg-to-pdf',
    name: 'JPG → PDF',
    icon: '🖼️',
    category: 'Essentials',
    desc: 'Convert images to PDF format',
    slug: 'jpg-to-pdf',
    colorBg: '#FFF0DC',
  },
  {
    id: 'word-to-pdf',
    name: 'Word → PDF',
    icon: '📄',
    category: 'Essentials',
    desc: 'Secure Word to PDF conversion',
    slug: 'word-to-pdf',
    colorBg: '#FFF0DC',
  },
  {
    id: 'pdf-to-word',
    name: 'PDF → Word',
    icon: '📝',
    category: 'Essentials',
    desc: 'Convert PDF back to editable Word',
    slug: 'pdf-to-word',
    colorBg: '#FFF0DC',
  },
  {
    id: 'rotate-pdf',
    name: 'Rotate PDF',
    icon: '🔄',
    category: 'Essentials',
    desc: 'Rotate pages individually or all',
    slug: 'rotate-pdf',
    colorBg: '#FFF0DC',
  },
  {
    id: 'organize-pages',
    name: 'Organize Pages',
    icon: '📋',
    category: 'Essentials',
    desc: 'Reorder, delete or rotate pages',
    slug: 'organize-pages',
    colorBg: '#FFF0DC',
  },
  {
    id: 'crop-pdf',
    name: 'Crop PDF',
    icon: '✂️',
    category: 'Essentials',
    desc: 'Crop margins from PDF pages',
    slug: 'crop-pdf',
    colorBg: '#FFF0DC',
  },
  {
    id: 'create-pdf',
    name: 'Create PDF',
    icon: '🆕',
    category: 'Essentials',
    desc: 'Create a PDF from scratch',
    slug: 'create-pdf',
    colorBg: '#FFF0DC',
  },

  // ── Edit & Organize ─────────────────────────────────────────────────────────
  {
    id: 'edit-pdf',
    name: 'Edit PDF + Sign',
    icon: '✍️',
    category: 'Edit & Organize',
    desc: 'Add text, shapes and signatures',
    slug: 'edit-pdf',
    colorBg: '#DBEAFE',
  },
  {
    id: 'annotate-pdf',
    name: 'Annotate PDF',
    icon: '💬',
    category: 'Edit & Organize',
    desc: 'Highlight and comment on PDFs',
    slug: 'annotate-pdf',
    colorBg: '#DBEAFE',
  },
  {
    id: 'add-watermark',
    name: 'Add Watermark',
    icon: '💧',
    category: 'Edit & Organize',
    desc: 'Stamp text or image over PDF',
    slug: 'add-watermark',
    colorBg: '#DBEAFE',
  },
  {
    id: 'add-page-numbers',
    name: 'Page Numbers',
    icon: '🔢',
    category: 'Edit & Organize',
    desc: 'Insert numbers with custom style',
    slug: 'add-page-numbers',
    colorBg: '#DBEAFE',
  },
  {
    id: 'add-header-footer',
    name: 'Header & Footer',
    icon: '📰',
    category: 'Edit & Organize',
    desc: 'Add custom headers and footers',
    slug: 'add-header-footer',
    colorBg: '#DBEAFE',
  },
  {
    id: 'add-bookmarks',
    name: 'Add Bookmarks',
    icon: '🔖',
    category: 'Edit & Organize',
    desc: 'Create navigation bookmarks',
    slug: 'add-bookmarks',
    colorBg: '#DBEAFE',
  },
  {
    id: 'redact-pdf',
    name: 'Redact PDF',
    icon: '⬛',
    category: 'Edit & Organize',
    desc: 'Permanently hide sensitive info',
    slug: 'redact-pdf',
    colorBg: '#DBEAFE',
  },
  {
    id: 'flatten-pdf',
    name: 'Flatten PDF',
    icon: '📐',
    category: 'Edit & Organize',
    desc: 'Remove forms and annotations',
    slug: 'flatten-pdf',
    colorBg: '#DBEAFE',
  },
  {
    id: 'cut-pdf',
    name: 'Cut PDF',
    icon: '🔪',
    category: 'Edit & Organize',
    desc: 'Cut pages in half — H or V',
    slug: 'cut-pdf',
    colorBg: '#DBEAFE',
    isNew: true,
  },
  {
    id: 'remove-pages-from-pdf',
    name: 'Remove Pages',
    icon: '🗑️',
    category: 'Edit & Organize',
    desc: 'Delete specific pages from PDF',
    slug: 'remove-pages-from-pdf',
    colorBg: '#DBEAFE',
  },
  {
    id: 'add-blank-page',
    name: 'Add Blank Page',
    icon: '📄',
    category: 'Edit & Organize',
    desc: 'Insert blank pages anywhere',
    slug: 'add-blank-page',
    colorBg: '#DBEAFE',
  },
  {
    id: 'add-pages-to-pdf',
    name: 'Add Pages',
    icon: '➕',
    category: 'Edit & Organize',
    desc: 'Insert pages from another PDF',
    slug: 'add-pages-to-pdf',
    colorBg: '#DBEAFE',
  },
  {
    id: 'edit-pdf-metadata',
    name: 'Edit Metadata',
    icon: '🏷️',
    category: 'Edit & Organize',
    desc: 'Edit title, author, keywords',
    slug: 'edit-pdf-metadata',
    colorBg: '#DBEAFE',
  },
  {
    id: 'remove-blank-pages',
    name: 'Remove Blank Pages',
    icon: '🧹',
    category: 'Edit & Organize',
    desc: 'Auto-detect and remove blanks',
    slug: 'remove-blank-pages',
    colorBg: '#DBEAFE',
  },
  {
    id: 'invert-pdf',
    name: 'Invert PDF',
    icon: '🌗',
    category: 'Edit & Organize',
    desc: 'Dark mode — invert all colors',
    slug: 'invert-pdf',
    colorBg: '#DBEAFE',
  },

  // ── Security ────────────────────────────────────────────────────────────────
  {
    id: 'encrypt-pdf',
    name: 'Encrypt PDF',
    icon: '🔐',
    category: 'Security',
    desc: 'Protect with strong password',
    slug: 'encrypt-pdf',
    colorBg: '#FEE2E2',
  },
  {
    id: 'remove-password',
    name: 'Remove Password',
    icon: '🔓',
    category: 'Security',
    desc: 'Unlock password-protected PDFs',
    slug: 'remove-password',
    colorBg: '#FEE2E2',
  },
  {
    id: 'privacy-scanner',
    name: 'Privacy Scanner',
    icon: '🔍',
    category: 'Security',
    desc: 'Find hidden metadata and text',
    slug: 'privacy-scanner',
    colorBg: '#FEE2E2',
  },
  {
    id: 'fingerprint-pdf',
    name: 'Fingerprint PDF',
    icon: '🪪',
    category: 'Security',
    desc: 'Embed invisible tracking info',
    slug: 'fingerprint-pdf',
    colorBg: '#FEE2E2',
  },

  // ── Convert ─────────────────────────────────────────────────────────────────
  {
    id: 'html-to-pdf',
    name: 'HTML → PDF',
    icon: '🌐',
    category: 'Convert',
    desc: 'Webpages to document format',
    slug: 'html-to-pdf',
    colorBg: '#D1FAE5',
  },
  {
    id: 'markdown-to-pdf',
    name: 'Markdown → PDF',
    icon: 'Md',
    category: 'Convert',
    desc: 'Convert Markdown to polished PDF',
    slug: 'markdown-to-pdf',
    colorBg: '#D1FAE5',
  },
  {
    id: 'excel-to-pdf',
    name: 'Excel → PDF',
    icon: '📊',
    category: 'Convert',
    desc: 'Spreadsheets to readable PDFs',
    slug: 'excel-to-pdf',
    colorBg: '#D1FAE5',
  },
  {
    id: 'csv-to-pdf',
    name: 'CSV → PDF',
    icon: '📋',
    category: 'Convert',
    desc: 'Convert CSV data to PDF table',
    slug: 'csv-to-pdf',
    colorBg: '#D1FAE5',
  },
  {
    id: 'text-to-pdf',
    name: 'Text → PDF',
    icon: '📃',
    category: 'Convert',
    desc: 'Convert plain text to PDF',
    slug: 'text-to-pdf',
    colorBg: '#D1FAE5',
  },
  {
    id: 'pdf-to-epub',
    name: 'PDF → ePub',
    icon: '📚',
    category: 'Convert',
    desc: 'Convert PDF to eBook format',
    slug: 'pdf-to-epub',
    colorBg: '#D1FAE5',
  },
  {
    id: 'pdf-to-audio',
    name: 'PDF → Audio',
    icon: '🔊',
    category: 'Convert',
    desc: 'Text-to-speech from PDF',
    slug: 'pdf-to-audio',
    colorBg: '#D1FAE5',
  },
  {
    id: 'pdf-to-json',
    name: 'PDF → JSON',
    icon: '{}',
    category: 'Convert',
    desc: 'Extract structured data for devs',
    slug: 'pdf-to-json',
    colorBg: '#D1FAE5',
    isNew: true,
  },
  {
    id: 'pdf-to-markdown',
    name: 'PDF → Markdown',
    icon: 'Md',
    category: 'Convert',
    desc: 'Convert PDF to Markdown format',
    slug: 'pdf-to-markdown',
    colorBg: '#D1FAE5',
    isNew: true,
  },
  {
    id: 'pdf-to-text',
    name: 'PDF → Text',
    icon: '📝',
    category: 'Convert',
    desc: 'Extract all text from PDF',
    slug: 'pdf-to-text',
    colorBg: '#D1FAE5',
  },
  {
    id: 'pdfs-to-zip',
    name: 'PDFs to ZIP',
    icon: '🗜️',
    category: 'Convert',
    desc: 'Bundle multiple PDFs into ZIP',
    slug: 'pdfs-to-zip',
    colorBg: '#D1FAE5',
    isNew: true,
  },
  {
    id: 'pdf-imposition',
    name: 'PDF Imposition',
    icon: '🖨️',
    category: 'Convert',
    desc: 'N-up printing layout for PDFs',
    slug: 'pdf-imposition',
    colorBg: '#D1FAE5',
  },
  {
    id: 'pdf-to-booklet',
    name: 'PDF to Booklet',
    icon: '📓',
    category: 'Convert',
    desc: 'Arrange pages for booklet print',
    slug: 'pdf-to-booklet',
    colorBg: '#D1FAE5',
  },
  {
    id: 'pdf-to-grayscale',
    name: 'PDF to Grayscale',
    icon: '◑',
    category: 'Convert',
    desc: 'Convert colour PDF to B&W',
    slug: 'pdf-to-grayscale',
    colorBg: '#D1FAE5',
    isNew: true,
  },
  {
    id: 'image-to-pdf',
    name: 'Image → PDF',
    icon: '🖼️',
    category: 'Convert',
    desc: 'Convert any image to PDF',
    slug: 'image-to-pdf',
    colorBg: '#D1FAE5',
  },
  {
    id: 'png-to-pdf',
    name: 'PNG → PDF',
    icon: '🖼️',
    category: 'Convert',
    desc: 'Convert PNG images to PDF',
    slug: 'png-to-pdf',
    colorBg: '#D1FAE5',
  },
  {
    id: 'pdf-to-png',
    name: 'PDF → PNG',
    icon: '🖼️',
    category: 'Convert',
    desc: 'Export PDF pages as PNG',
    slug: 'pdf-to-png',
    colorBg: '#D1FAE5',
  },
  {
    id: 'pdf-to-webp',
    name: 'PDF → WebP',
    icon: '🖼️',
    category: 'Convert',
    desc: 'Export PDF pages as WebP',
    slug: 'pdf-to-webp',
    colorBg: '#D1FAE5',
  },
  {
    id: 'pdf-to-tiff',
    name: 'PDF → TIFF',
    icon: '🖼️',
    category: 'Convert',
    desc: 'Export PDF pages as TIFF',
    slug: 'pdf-to-tiff',
    colorBg: '#D1FAE5',
  },
  {
    id: 'svg-to-pdf',
    name: 'SVG → PDF',
    icon: '🎨',
    category: 'Convert',
    desc: 'Convert SVG vector files to PDF',
    slug: 'svg-to-pdf',
    colorBg: '#D1FAE5',
  },
  {
    id: 'webp-to-pdf',
    name: 'WebP → PDF',
    icon: '🖼️',
    category: 'Convert',
    desc: 'Convert WebP images to PDF',
    slug: 'webp-to-pdf',
    colorBg: '#D1FAE5',
  },
  {
    id: 'heif-to-pdf',
    name: 'HEIF → PDF',
    icon: '📷',
    category: 'Convert',
    desc: 'Convert HEIC/HEIF photos to PDF',
    slug: 'heif-to-pdf',
    colorBg: '#D1FAE5',
  },

  // ── AI Tools ────────────────────────────────────────────────────────────────
  {
    id: 'ocr-pdf',
    name: 'OCR PDF',
    icon: '👁️',
    category: 'AI Tools',
    desc: 'Make scanned text searchable',
    slug: 'ocr-pdf',
    colorBg: '#EDE9FE',
    ai: true,
  },
  {
    id: 'chat-with-pdf',
    name: 'Chat with PDF',
    icon: '💬',
    category: 'AI Tools',
    desc: 'Ask questions about your doc',
    slug: 'chat-with-pdf',
    colorBg: '#EDE9FE',
    ai: true,
  },
  {
    id: 'ai-summarizer',
    name: 'AI Summarizer',
    icon: '🤖',
    category: 'AI Tools',
    desc: 'Get key points instantly',
    slug: 'ai-summarizer',
    colorBg: '#EDE9FE',
    ai: true,
  },
  {
    id: 'compare-pdfs',
    name: 'Compare PDFs',
    icon: '⚖️',
    category: 'AI Tools',
    desc: 'Page-by-page diff of two PDFs',
    slug: 'compare-pdfs',
    colorBg: '#EDE9FE',
    ai: true,
  },
  {
    id: 'remove-background',
    name: 'Remove BG',
    icon: '🎨',
    category: 'AI Tools',
    desc: 'Clear image backgrounds instantly',
    slug: 'remove-background',
    colorBg: '#EDE9FE',
    ai: true,
  },
  {
    id: 'repair-pdf',
    name: 'Repair PDF',
    icon: '🔧',
    category: 'AI Tools',
    desc: 'Fix corrupted PDF files',
    slug: 'repair-pdf',
    colorBg: '#EDE9FE',
    ai: true,
  },

  // ── Utilities ────────────────────────────────────────────────────────────────
  {
    id: 'pdf-viewer',
    name: 'PDF Viewer',
    icon: '👓',
    category: 'Utilities',
    desc: 'View PDFs with search and zoom',
    slug: 'pdf-viewer',
    colorBg: '#F3F4F6',
    isNew: true,
  },
  {
    id: 'pdf-word-counter',
    name: 'Word Counter',
    icon: '🔢',
    category: 'Utilities',
    desc: 'Count words in any PDF',
    slug: 'pdf-word-counter',
    colorBg: '#F3F4F6',
    isNew: true,
  },
  {
    id: 'compress-image',
    name: 'Compress Image',
    icon: '🗜️',
    category: 'Utilities',
    desc: 'Reduce image file size',
    slug: 'compress-image',
    colorBg: '#F3F4F6',
  },
  {
    id: 'gst-invoice',
    name: 'GST Invoice',
    icon: '🧾',
    category: 'Utilities',
    desc: 'Generate compliant invoices',
    slug: 'gst-invoice',
    colorBg: '#F3F4F6',
    in: true,
  },
  {
    id: 'pos-billing',
    name: 'POS Billing',
    icon: '🖨️',
    category: 'Utilities',
    desc: 'Quick thermal print receipts',
    slug: 'pos-billing',
    colorBg: '#F3F4F6',
    in: true,
  },
]
